import type { ProjectReportFinding, ProjectReportSnapshot } from './types.js';

function plainText(value: unknown): string {
  return String(value ?? '').replace(/[\u2010-\u2015\u2212]/g, '-');
}

function tableCell(value: unknown): string {
  return plainText(value).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

function inlineCode(value: unknown): string {
  const tick = String.fromCharCode(96);
  return tick + plainText(value).replace(new RegExp(tick, 'g'), '\\' + tick) + tick;
}

function date(value: string | null | undefined): string {
  if (!value) return 'Unavailable';
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? plainText(value) : parsed.toISOString();
}

function titleForStatus(status: string): string {
  const known: Record<string, string> = {
    new: 'New', carryover: 'Carryover', accepted: 'Accepted', dismissed: 'Dismissed', fixed: 'Fixed',
    success: 'Completed', failure: 'Failed', failed: 'Failed', blocked: 'Needs attention',
    cancelled: 'Cancelled', pending_approval: 'Need approval', completed: 'Completed',
    approved: 'Completed', changes_requested: 'Changes requested', queued: 'Queued', running: 'In progress',
  };
  return known[status] ?? plainText(status);
}

function reviewState(snapshot: ProjectReportSnapshot): string {
  const review = snapshot.latestReview;
  if (!review) return 'Unavailable';
  if (review.decision?.decision === 'approved') return 'Completed';
  if (review.decision?.decision === 'changes_requested') return 'Changes requested';
  if (review.session.status === 'success') return 'Need approval';
  return titleForStatus(review.session.status);
}

function appendFinding(lines: string[], finding: ProjectReportFinding, index: number): void {
  lines.push('### ' + String(index + 1) + '. ' + plainText(finding.title), '');
  lines.push('- **Risk level:** ' + plainText(finding.riskLevel ?? 'Not classified'));
  lines.push('- **Severity:** ' + plainText(finding.severity));
  lines.push('- **Priority:** ' + plainText(finding.priority ?? 'Not supplied'));
  lines.push('- **State:** ' + titleForStatus(finding.status));
  lines.push('- **Source module:** ' + plainText(finding.source));
  lines.push('- **Category:** ' + plainText(finding.category));
  lines.push('- **Finding ID:** ' + inlineCode(finding.id));
  if (finding.filePath) lines.push('- **Location:** ' + inlineCode(finding.filePath + (finding.lineNumber ? ':' + finding.lineNumber : '')));
  if (finding.artifactId) lines.push('- **Artifact ID:** ' + inlineCode(finding.artifactId));
  lines.push('- **Created:** ' + date(finding.createdAt));
  if (finding.confidence) lines.push('- **Confidence:** ' + plainText(finding.confidence));
  lines.push('');
  lines.push(plainText(finding.description || 'No description was supplied.'), '');
  if (finding.evidenceText) {
    const fence = finding.evidenceText.includes('~~~') ? '~~~~' : '~~~';
    lines.push('**Evidence:**', '', fence, plainText(finding.evidenceText), fence, '');
  }
  if (finding.recommendation) lines.push('**Recommendation:** ' + plainText(finding.recommendation), '');
}

function appendUsage(lines: string[], usage: ProjectReportSnapshot['modelUsage']): void {
  if (usage.status !== 'available' || !usage.totals) {
    lines.push('*Usage unavailable: ' + plainText(usage.reason ?? 'No model-usage records were persisted.') + '*', '');
    return;
  }
  lines.push(
    '| Calls | Input tokens | Output tokens | Cache reads | Cache creation |',
    '| ---: | ---: | ---: | ---: | ---: |',
    '| ' + usage.totals.calls + ' | ' + usage.totals.input + ' | ' + usage.totals.output + ' | ' + usage.totals.cacheRead + ' | ' + usage.totals.cacheCreation + ' |',
    '',
  );
  if (usage.byModel.length) {
    lines.push('| Provider | Model | Calls | Input | Output | Cache reads | Cache creation |', '| --- | --- | ---: | ---: | ---: | ---: | ---: |');
    usage.byModel.forEach(group => lines.push(
      '| ' + tableCell(group.provider) + ' | ' + tableCell(group.model) + ' | ' + group.calls + ' | ' + group.input + ' | ' + group.output + ' | ' + group.cacheRead + ' | ' + group.cacheCreation + ' |',
    ));
    lines.push('');
  }
}

export function renderProjectReportMarkdown(snapshot: ProjectReportSnapshot): string {
  const lines: string[] = [
    '# Project report',
    '',
    '**Project:** ' + plainText(snapshot.project.name),
    '**Project ID:** ' + inlineCode(snapshot.project.id),
    '**Generated:** ' + date(snapshot.metadata.generatedAt),
    '**Generated by:** ' + (snapshot.metadata.actorId ? inlineCode(snapshot.metadata.actorId) : 'Unavailable'),
    '**Export ID:** ' + inlineCode(snapshot.metadata.reportId),
    '**Generator version:** ' + inlineCode(snapshot.metadata.generatorVersion),
    '**Risk policy version:** ' + inlineCode(snapshot.metadata.riskPolicyVersion),
    '**Description:** ' + plainText(snapshot.project.description || 'No description supplied.'),
    '',
    'This immutable export renders JSON, Markdown, and PDF from one report snapshot. It contains project-level findings and the latest available Review and Dynamic Test summaries. No model prompts, credentials, or hidden reasoning are included.',
    '',
    '## Risk assessment',
    '',
    '**Policy:** ' + inlineCode(snapshot.riskAssessment.policyVersion),
    '**Current static risk items:** ' + snapshot.riskAssessment.currentFindingCount,
    '',
    '| Critical | High | Medium | Low | Unclassified |',
    '| ---: | ---: | ---: | ---: | ---: |',
    '| ' + snapshot.riskAssessment.critical + ' | ' + snapshot.riskAssessment.high + ' | ' + snapshot.riskAssessment.medium + ' | ' + snapshot.riskAssessment.low + ' | ' + snapshot.riskAssessment.unclassified + ' |',
    '',
    'The risk summary uses the shared Centinel assessment policy. Dynamic findings remain in the finding inventory and are not included in this static risk summary.',
    '',
  ];

  if (snapshot.riskAssessment.items.length) {
    lines.push('| Risk level | Severity | Priority | State | Finding |', '| --- | --- | --- | --- | --- |');
    snapshot.riskAssessment.items.forEach(finding => lines.push(
      '| ' + tableCell(finding.riskLevel ?? 'Not classified')
      + ' | ' + tableCell(finding.severity)
      + ' | ' + tableCell(finding.priority ?? 'Not supplied')
      + ' | ' + tableCell(titleForStatus(finding.status))
      + ' | ' + tableCell(finding.title) + ' |',
    ));
    lines.push('');
  } else {
    lines.push('*No current risk items are available.*', '');
  }

  lines.push(
    '## Finding inventory',
    '',
    'Every persisted finding is included with its current state. New, accepted, and carryover findings remain distinct from fixed and dismissed findings.',
    '',
  );
  if (!snapshot.findings.length) lines.push('*No findings have been recorded.*', '');
  else snapshot.findings.forEach((finding, index) => appendFinding(lines, finding, index));

  lines.push('## Latest Static Review', '');
  if (!snapshot.latestReview) {
    lines.push('*Unavailable: no terminal Review record is available for this project.*', '');
  } else {
    const review = snapshot.latestReview;
    lines.push(
      '**Review:** ' + plainText(review.session.name),
      '**Review ID:** ' + inlineCode(review.session.id),
      '**Lifecycle state:** ' + reviewState(snapshot),
      '**Execution status:** ' + titleForStatus(review.session.status),
      '**Decision:** ' + (review.decision ? titleForStatus(review.decision.decision) : 'No decision recorded'),
      '**Created:** ' + date(review.session.createdAt),
      '**Updated:** ' + date(review.session.updatedAt),
      '**Summary:** ' + plainText(review.summary || 'No summary was recorded.'),
      '',
    );
    if (review.session.failureReason) lines.push('**Failure reason:** ' + plainText(review.session.failureReason), '');
    if (review.decision?.comment) lines.push('**Decision feedback:** ' + plainText(review.decision.comment), '');
    if (review.decision?.reviewer) lines.push('**Reviewer:** ' + plainText(review.decision.reviewer), '');
    if (review.decision?.attachments.length) {
      lines.push('### Decision attachments', '');
      review.decision.attachments.forEach(item => lines.push('- ' + plainText(item.fileName) + ' (' + plainText(item.mimeType) + ') - ' + date(item.createdAt)));
      lines.push('');
    }

    lines.push('### Reported findings', '');
    if (!review.reportedFindings.length) lines.push('*No newly reported findings are persisted for this Review.*', '');
    else review.reportedFindings.forEach((finding, index) => appendFinding(lines, finding, index));

    lines.push('### Carryover findings', '');
    if (!review.carryoverFindings.length) lines.push('*No carryover findings are persisted for this Review.*', '');
    else review.carryoverFindings.forEach((finding, index) => appendFinding(lines, finding, index));
    if (review.findingClassificationStatus === 'unavailable') {
      lines.push('*Recurring and other cross-Review classifications are unavailable for this record and are not inferred.*', '');
    } else {
      lines.push('**Cross-Review classification:** available', '');
      if (review.recurringFindings?.length) lines.push('**Recurring findings:** ' + review.recurringFindings.length, '');
      if (review.correlations?.length) {
        lines.push('| Classification | Method | Score | Finding |', '| --- | --- | ---: | --- |');
        review.correlations.forEach(item => lines.push(
          '| ' + tableCell(item.classification) + ' | ' + tableCell(item.method) + ' | ' + item.score + ' | ' + tableCell(item.childFindingId ?? item.parentFindingId ?? 'Unavailable') + ' |',
        ));
        lines.push('');
      }
    }
    lines.push(
      '### Source manifest',
      '',
      '**Status:** ' + titleForStatus(review.sourceManifest.status),
      '**Captured:** ' + date(review.sourceManifest.capturedAt),
      '**Artifacts reviewed:** ' + (review.sourceManifest.artifactCount === null ? 'Unavailable' : review.sourceManifest.artifactCount),
      '',
    );
    if (review.sourceManifest.sources.length) {
      lines.push('| Source | Kind | Files | Content hashes |', '| --- | --- | ---: | --- |');
      review.sourceManifest.sources.forEach(source => lines.push(
        '| ' + tableCell(source.label)
        + ' | ' + tableCell(source.sourceKind)
        + ' | ' + source.filesReviewed
        + ' | ' + tableCell(source.contentHashes.join(', ') || 'Unavailable') + ' |',
      ));
      lines.push('');
    } else {
      lines.push('*No source-manifest items are available.*', '');
    }

    lines.push('### Traceability', '');
    lines.push('**Status:** ' + titleForStatus(review.traceability.status), '');
    if (review.traceability.summary) {
      lines.push(
        '**Complete:** ' + review.traceability.summary.complete,
        '**Incomplete:** ' + review.traceability.summary.incomplete,
        '**Missing:** ' + review.traceability.summary.missing,
        '**Attention:** ' + review.traceability.summary.attention,
        '',
      );
    } else {
      lines.push('*Unavailable: this Review has no persisted traceability snapshot.*', '');
    }
    if (review.traceability.records.length) {
      lines.push('| Requirement | State | Mappings | Source artifacts | Confidence |', '| --- | --- | ---: | --- | ---: |');
      review.traceability.records.forEach(record => lines.push(
        '| ' + tableCell(record.title)
        + ' | ' + tableCell(record.state)
        + ' | ' + record.mappingIds.length
        + ' | ' + tableCell(record.sourceArtifactIds.join(', ') || 'None')
        + ' | ' + (record.confidence === null ? 'Unavailable' : record.confidence) + ' |',
      ));
      lines.push('');
    }

    lines.push('### Review model usage', '');
    appendUsage(lines, review.modelUsage);
  }

  lines.push('## Project sources', '');
  lines.push('**Source records available:** ' + snapshot.sourceInventory.artifactCount, '');
  if (!snapshot.sourceInventory.artifacts.length) lines.push('*No source artifacts are recorded.*', '');
  else {
    lines.push('| Source | Type | Origin | Content hash | Recorded |', '| --- | --- | --- | --- | --- |');
    snapshot.sourceInventory.artifacts.forEach(artifact => lines.push(
      '| ' + tableCell(artifact.fileName)
      + ' (' + tableCell(artifact.path) + ')'
      + ' | ' + tableCell(artifact.type)
      + ' | ' + tableCell(artifact.source)
      + ' | ' + inlineCode(artifact.contentHash)
      + ' | ' + date(artifact.createdAt) + ' |',
    ));
    lines.push('');
  }

  lines.push('## Requirements', '');
  if (!snapshot.requirements.items.length) lines.push('*No structured requirements are recorded.*', '');
  else {
    snapshot.requirements.items.forEach(requirement => {
      lines.push('### ' + plainText(requirement.title), '');
      lines.push('- **Requirement ID:** ' + inlineCode(requirement.id));
      lines.push('- **Category:** ' + plainText(requirement.category || 'Not supplied'));
      lines.push('- **Priority:** ' + plainText(requirement.priority || 'Not supplied'));
      lines.push('- **Mappings:** ' + requirement.mappings.length);
      requirement.mappings.forEach(mapping => lines.push(
        '  - ' + plainText(mapping.coverageStatus)
        + ' (confidence ' + mapping.confidence + '; artifact ' + inlineCode(mapping.fileId ?? 'Unavailable') + ')',
      ));
      if (requirement.description) lines.push('', plainText(requirement.description));
      lines.push('');
    });
  }

  lines.push('## Coding standards', '');
  if (!snapshot.standards.items.length) lines.push('*No coding-standard artifacts are recorded.*', '');
  else {
    snapshot.standards.items.forEach(standard => {
      lines.push('- **' + plainText(standard.title) + '** - ' + tableCell(standard.path) + ' (' + plainText(standard.source) + ')');
      lines.push('  - Content hash: ' + inlineCode(standard.contentHash));
      lines.push('  - Structured-rule state: ' + standard.structuredRulesStatus + '.');
      if (standard.rules?.length) {
        standard.rules.filter(rule => rule.enabled).forEach(rule => lines.push('    - ' + tableCell(rule.stableKey) + ': ' + tableCell(rule.statement)));
      }
    });
    lines.push('');
  }

  lines.push('## Model usage summary', '');
  appendUsage(lines, snapshot.modelUsage);
  lines.push('Usage contains provider/model and token counts only. Credentials, prompts, model responses, and hidden reasoning are excluded.', '');

  lines.push('## Latest existing Dynamic Test', '');
  if (!snapshot.latestDynamicTest) {
    lines.push('*Unavailable: no terminal Dynamic Test summary is available for this project.*', '');
  } else {
    const dynamic = snapshot.latestDynamicTest;
    lines.push(
      '**Test:** ' + plainText(dynamic.session.name),
      '**Test ID:** ' + inlineCode(dynamic.session.id),
      '**Status:** ' + titleForStatus(dynamic.session.status),
      '**Target:** ' + plainText(dynamic.session.targetUrl),
      '**Goal:** ' + plainText(dynamic.session.goal),
      '**Mission:** ' + plainText(dynamic.session.missionType),
      '**Created:** ' + date(dynamic.session.createdAt),
      '**Updated:** ' + date(dynamic.session.updatedAt),
      '**Summary:** ' + plainText(dynamic.summary || 'No summary was recorded.'),
      '',
    );
    if (dynamic.failureReason) lines.push('**Failure reason:** ' + plainText(dynamic.failureReason), '');
    lines.push('### Evidence references', '');
    if (!dynamic.evidence.length) lines.push('*No evidence references are recorded.*', '');
    else {
      lines.push('| Type | Summary | Location | Recorded |', '| --- | --- | --- | --- |');
      dynamic.evidence.forEach(item => lines.push(
        '| ' + tableCell(item.type)
        + ' | ' + tableCell(item.summary)
        + ' | ' + (item.path ? inlineCode(item.path) : 'Unavailable')
        + ' | ' + date(item.createdAt) + ' |',
      ));
      lines.push('');
    }
    lines.push('### Action trace', '');
    if (!dynamic.actionTrace.length) lines.push('*No action trace is available.*', '');
    else {
      lines.push('| Step | Action | Target | Result |', '| ---: | --- | --- | --- |');
      dynamic.actionTrace.forEach(item => lines.push(
        '| ' + item.step + ' | ' + tableCell(item.action) + ' | ' + tableCell(item.target) + ' | ' + tableCell(item.result) + ' |',
      ));
      lines.push('');
    }
    lines.push('Raw console output and model request/response payloads are not included in this report.', '');
  }

  lines.push('---', '', 'Snapshot JSON: ' + inlineCode(snapshot.metadata.outputFiles.json));
  lines.push('Markdown: ' + inlineCode(snapshot.metadata.outputFiles.markdown));
  lines.push('PDF: ' + inlineCode(snapshot.metadata.outputFiles.pdf), '');
  return lines.join('\n');
}
